### ISSUE TITLE
Grilla en detalle de recetas

### ISSUE THREAD

**Issue by hbaravalle** [pirry007/proyecto-modulo-1#1]
Miguel! Revisando el proyecto encuentro que llegado un punto de tamaño de pantalla, parte de la info de ambas columnas de lo que es el detalle de una receta, se pierde un poco. Para arreglarlo seguramente podrías cambiar el valor de grid-template-columns de porcentajes a fr's. Te dejo una captura de pantalla a un tamaño de 820px:

![image](https://github.com/pirry007/proyecto-modulo-1/assets/24690415/1d8abb22-b5d3-4c7a-8277-adc6876ba237)

**Comment by pirry007** [comment]
hola profe, gracias por la observación, pero ya lo tengo puesto con fr's y
sigue lo mismo, no se me ocurre como podria solucionar eso

**Comment by pirry007** [comment]
ahh si, gracias profe por la observación, ya lo solucione
